export const updateAuditFields = ["ModifiedBy", "ModifiedDate"];
export const auditFields = [
  "Id",
  "CreatedBy",
  "CreatedDate",
  "ModifiedBy",
  "ModifiedDate",
];

export const objectFields = {
  dealers: [
    "Name",
    "Phone",
    "Email",
    "Country",
    "State",
    "District",
    "PinCode",
    "Street",
    "OwnerName",
  ],
  customers: [
    "FirstName",
    "LastName",
    "Email",
    "Phone",
    "Country",
    "State",
    "Agent",
    "Hirer",
    "Guarantor",
    "Referrer",
    "District",
    "PinCode",
    "Street",
    "Dealer",
    "DateOfBirth",
  ],
  brands: ["Name", "Description"],
  products: [
    "Name",
    "Code",
    "CCPower",
    "ModelMonth",
    "ModelYear",
    "Description",
    "BrandId",
  ],
  loans: [
    "Dealer",
    "Agent",
    "DealerFileNumber",
    "ConditionType",
    "Model",
    "ModelMonth",
    "ModelYear",
    "CCPower",
    "InsuranceType",
    "ChasisNo",
    "EngineNo",
    "RegistrationNo",
    "Color",
    "TotalPrice",
    "DownPayment",
    "DisburseAmount",
    "RateOfInterest",
    "Tenure",
    "EMIAmount",
    "RemainingAmountWithInterest",
    "FileCharge",
    "RTOCharge",
    "DealerComission",
    "AgentComission",
    "AgreementDate",
    "FirstAutoDebitDate",
    "EMIStartDate",
    "EMIEndDate",
    "PaymentOptions",
    "Hirer",
    "Guarantor",
    "Referrer1",
    "Referrer2",
    "NOCDate",
    "BillNo",
    "RCNo",
    "KeyNo",
    "InsurancePolicyNo",
    "InsuranceCompanyName",
    "CustomerBankName",
    "BankIFSC",
    "BankMICR",
    "BankAccountNumber",
    "BankBranchName",
    "AccountType",
    "CustomerBankPhoneNumber",
    "NumberOfCheques",
    "ChequeNumber1",
    "ChequeNumber2",
    "ChequeNumber3",
    "ChequeNumber4",
    "ChequeNumber5",
    "Description",
  ],
  pricebookentry: ["Pricebook", "Isactive", "Unitprice", "Product"],
  pricebook: ["Dealer","IsActive"],
};
