import { helperMethods } from "./CMPhelper";
export const documentData = [
  {
    Name: "Photo",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Voter's ID",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Stamp/Cheque",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "29, 30 Form",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Vehicle's Bill",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Vehicle's Insurance",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Vehicle's Key",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Ecs Fixed",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
  {
    Name: "Ecs Max",
    Version: 0,
    CreatedBy: helperMethods.fetchUser(),
    CreatedDate: helperMethods.dateToString(),
    ModifiedBy: helperMethods.fetchUser(),
    ModifiedDate: helperMethods.dateToString(),
  },
];
